#!/bin/sh

OZFLYMAKEPATH=`dirname $0`

if ozengine $OZFLYMAKEPATH/IsFunctor.ozf $1; then
    ozc -c $1 2>&1 | ozengine $OZFLYMAKEPATH/PostprocessErrors.ozf
    if [[ -e $1ff ]];then
	rm $1ff
    fi
else
    ozengine $OZFLYMAKEPATH/OPISyntaxChecker.ozf $1 2>&1 | ozengine $OZFLYMAKEPATH/PostprocessErrors.ozf
fi
if [ $2 == "t" ]
then
    ozengine $OZFLYMAKEPATH/CheckArity.ozf --source $1 2>&1 | ozengine $OZFLYMAKEPATH/PostprocessErrors.ozf
fi
exit 0
